#! /bin/bash
# standalone compilation
make -j -f makefile.en V=1 app
# remove relocations in the app (save about 600Ko)
g++ reloc.cc -o reloc
cd bin
../reloc DEMO.bin
cd ..
# build 8ek and segments appvar for INST
python3 app_tools/make_8ek.py bin/_DEMO.bin bin/DEMO.8ek DEMO
python3 app_tools/make_segments.py bin/_DEMO.bin bin
echo "English done"
# local install, assumes you have a link to a folder shared/ti with artifice
/bin/cp bin/DEMO.8* shared/ti
rm -rf shared/ti/app && mkdir -p shared/ti/app && cp bin/App*x* shared/ti/app 
echo "Running ./bundle84 to make khicas84.b84 (or ./bundle83 to test English on a 83)"
./bundle84
ls -l shared/ti/DEMO.8ek
