#! /bin/bash
# standalone compilation
#/bin/cp ../meta/makefile.mk .
#/bin/cp makefile.mk.nolibs ../meta/makefile.mk
ln -sf app_tools/app_src2 app_tools/app_src
make -j -f makefile.fr V=1 app
ln -sf app_tools/app_src1 app_tools/app_src
#/bin/cp makefile.mk ../meta
# remove relocations in the app (save about 600Ko)
g++ reloc.cc -o reloc
cd bin
../reloc DEMO.bin
cd ..
# build 8ek and segments appvar for INST
python3 app_tools/make_8ek.py bin/_DEMO.bin bin/DEMO.8ek DEMO
python3 app_tools/make_segments.py bin/_DEMO.bin bin
echo "Francais done"
# local install, assumes you have a link to a folder shared/ti with artifice
/bin/cp bin/DEMO.8* shared/ti
rm -rf shared/ti/app && mkdir -p shared/ti/app && cp bin/App*x* shared/ti/app 
echo "Running ./bundle83 to make khicas83.b83 (run ./bundle84 to test French on a 84)"
./bundle83
ls -l shared/ti/DEMO.8ek
