name: Continuous integration
on:
  push:
jobs:
  KhiCAS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build CE toolchain
        run: |
          git clone --recursive https://github.com/CE-Programming/toolchain.git
          cd toolchain
          git checkout f92e4d0a12da1e7b7ced3c7dbba0e5d9727b8add
          wget -q https://github.com/CE-Programming/llvm-project/releases/download/nightly/ez80-clang-link_ubuntu_nightly.zip && unzip -q ez80-clang-link_ubuntu_nightly.zip && rm ez80-clang-link_ubuntu_nightly.zip && sudo mv ez80-* /usr/local/bin/
          wget -q https://flatassembler.net/fasmg.kp60.zip && unzip -q fasmg.kp60.zip && sudo mv fasmg.x64 /usr/local/bin/fasmg && rm fasmg*
          cp ../allocator_standard.c src/libc/
          make
          make install DESTDIR=$PWD
          sed -i '/-i $(call QUOTE_ARG,library $(LDLIBS))/d' CEdev/meta/makefile.mk
          sudo mv /usr/local/bin/fasmg /usr/local/bin/ez80-* CEdev/bin/
      - name: Build KhiCAS
        run: |
          export PATH=$PWD/toolchain/CEdev/bin:$PATH
          pwd && ls -l
          ./mkappfr
      - uses: actions/upload-artifact@v4
        with:
          name: KhiCAS
          path: bin/*
