name: Continuous integration
on:
  push:
jobs:
  KhiCAS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./mkappfr
      - uses: actions/upload-artifact@v4
        with:
          name: DEMO.8ek
          path: shared/ti/DEMO.8ek
