name: Continuous integration
on:
  push:
jobs:
  KhiCAS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: |
          wget -q https://github.com/CE-Programming/toolchain/releases/download/nightly/CEdev-Linux-nightly.tar.gz
          tar -xvf CEdev-Linux-nightly.tar.gz
          ls -l
      - run: ./mkappfr
      - uses: actions/upload-artifact@v4
        with:
          name: DEMO.8ek
          path: shared/ti/DEMO.8ek
